### ISSUE TITLE
Credit: drawer 

### ISSUE THREAD

**Issue by zooqueen** [luxfi/web#121]
<img width="1557" alt="Untitled 2" src="https://github.com/luxfi/web/assets/98129351/81aaa3df-027b-49eb-b39f-be26c8f1c66c">

Buy button on the main landing page just add the item to the cart, and drawer bottom appears, instead of this popup, (shown within the red box) 

If someone expands drawer this should appear
<img width="599" alt="Untitled 3" src="https://github.com/luxfi/web/assets/98129351/5fc0e24b-bc2f-4140-a74a-46849be13c26">

**Comment by artemis-prime** [comment]
Please leave more detailed verbal desc of what happens at each user action. Thx

**Comment by artemis-prime** [comment]
![WhatsApp Image 2024-03-26 at 7 25 16 AM](https://github.com/luxfi/web/assets/633467/64bcde3a-1504-4d1a-a4aa-075a59f22579)

**Comment by artemis-prime** [comment]
What about "buy" buttons on pages that don't have a variant selected?  Like the "Elite" page.   Then we need the select drawer (...on  mobile.  And whatever we decide on DT)

**Comment by zooqueen** [comment]
yes
