### ISSUE TITLE
Mobile Issues: Minor UI changes

### ISSUE THREAD

**Issue by zooqueen** [luxfi/web#132]
![IMG_2517](https://github.com/luxfi/web/assets/98129351/bbcff09f-4633-40ec-a6a9-3a8fc0fce409)

can we move up the font size for words in red box?? like 18-24 whatever looks good and can fit 

![IMG_2411](https://github.com/luxfi/web/assets/98129351/78f47f51-ffc4-406d-87af-80e3874bf8b4)

1. on compare card page remove circle and decrease size of + 
2. remove the circle around the +
3. Add a material selection choice for all black cards. Should be Anodized Titanium, and Black Gunmetal, you can download gunmetal file [here] Soooo the compare c ard page should show two color selection choices, not one 
(https://drive.google.com/drive/folders/1ON2Pwz9lIP0wBGVz-wXaSYstmXMFUL6Y?usp=drive_link)
![IMG_2411](https://github.com/luxfi/web/assets/98129351/fef03a88-c033-40fa-8a6f-27f3a4bde7c4)

**Comment by erikrakuscek** [comment]
What do you mean by "words in red box", I can't see a red box on screenshots

**Comment by zooqueen** [comment]
i added the screenshot seems like it wasn’t attached before @erikrakuscek
