### ISSUE TITLE
Credit: Changes to all cards and card details pages

### ISSUE THREAD

**Issue by erikrakuscek** [luxfi/web#144]
All cards page:
- Replace flat card images with new flat images created from 3D models
- "What are Karma Rewards?" should link to part in lux.docs that explains Karma Token. Please provide a link to the docs.
![image](https://github.com/luxfi/web/assets/17453589/4efe8ad7-f74e-4c0e-9365-09f555e5dc19)
- Provide links for "Offer & Benefit Terms" and "Rates and Fees" for each card
![image](https://github.com/luxfi/web/assets/17453589/cf86afd0-b0e8-4206-a1f2-7bdc1ed41e81)
~~- It should only show the first 4 benefits on mobile unless user clicks underlined "View All" which should expand to show all of the cards with images~~
![image](https://github.com/luxfi/web/assets/17453589/5ef93332-0873-4294-b039-5c3d8b2234bd)
~~- fix mobile iOS height bug in benefits section~~
![WhatsApp Image 2024-04-05 at 06 40 12_1f5417ff](https://github.com/luxfi/web/assets/17453589/3d43f6ab-69e0-433a-b828-d9bc0186ee8f)
~~- on tablet and desktop view, add a bar on top of card details page to switch between cards~~
![image](https://github.com/luxfi/web/assets/17453589/6c10b6c2-98a3-4ea3-997a-d096379c9f35)

**Comment by erikrakuscek** [comment]
This is on hold until we get the new flat cards version

**Comment by zeekay** [comment]
@erikrakuscek as I understand this is complete except new content?

**Comment by erikrakuscek** [comment]
> @erikrakuscek as I understand this is complete except new content?

Yes, only 3D flat cards images and those 3 links are still missing.
