### ISSUE TITLE
Change Lux Credit Video on Lux.network

### ISSUE THREAD

**Issue by zooqueen** [luxfi/web#150]
Change Lux Credit Video on Lux.network
<img width="1346" alt="Untitled 5" src="https://github.com/luxfi/web/assets/98129351/76ac71eb-87e9-473b-85bf-5bff666fef8a">

Change the Black Card to the new black card video that doesnt show visa

**Comment by erikrakuscek** [comment]
Fixed with commit https://github.com/luxfi/web/commit/6ccec5c6b21a915ff48e43bd729c9ccaf364ea5b
