### ISSUE TITLE
Lux Market: Change Card

### ISSUE THREAD

**Issue by zooqueen** [luxfi/web#158]
Change black card on https://lux.market/ to the new one without the visa, can you also try to slow down the speed of the animation to match the gold bars

-also slow down the speed of the black card on lux.network to match the gold/silver bars

**Comment by erikrakuscek** [comment]
The animation speed must be set in Spline I think.

**Comment by artemis-prime** [comment]
Please close if not possible @erikrakuscek

**Comment by erikrakuscek** [comment]
The animation speed should be adjusted by the designer in Spline.
