### ISSUE TITLE
Network: Open buy drawer on Nano Validator by default

### ISSUE THREAD

**Issue by erikrakuscek** [luxfi/web#167]
![image](https://github.com/luxfi/web/assets/17453589/6a710bb6-57e7-44c9-9b9d-c0de2d3c7bc9)

**Comment by artemis-prime** [comment]
@zeekay How about I add a setting to sort items in a Family buy cost, rather than natural order of data ?

**Comment by artemis-prime** [comment]
> @zeekay How about I add a setting to sort items in a Family buy cost, rather than natural order of data ?

This is now the default and in prod.

tl:dr; logic:  
Default: carousel for single-family (VL and CN)
  if carousel, default shows the slider (unless turned off explicitly)
  if slider, default is to sorted in 'asc' order  (unless turned off explicitly)
