### ISSUE TITLE
Commerce: Coin buy drawer as a slider/carousel

### ISSUE THREAD

**Issue by erikrakuscek** [luxfi/web#171]
fix the drawer to only have the Inter heading, hide the druk one

instead of this:

![image](https://github.com/luxfi/web/assets/17453589/f3dcb7be-de83-4924-901c-dfb4f5a455dd)

make similar to this:

![image](https://github.com/luxfi/web/assets/17453589/3d6e8d73-fe5a-4b14-b735-a17025afd018)

carousel should start at 1M option

**Comment by erikrakuscek** [comment]
stylize prices as
$111
$1.11K
$11.1K
$111.1K

![image](https://github.com/luxfi/web/assets/17453589/5f0766a9-6baa-4be4-a8c1-ef2fdd13fe50)

**Comment by artemis-prime** [comment]
fixed
