### ISSUE TITLE
credit: card clickthroughs

### ISSUE THREAD

**Issue by zooqueen** [luxfi/web#192]
<img width="1410" alt="l" src="https://github.com/luxfi/web/assets/98129351/600a3c18-3109-41c4-91f4-61c1726fb4d0">

1. can we make sure every time you click on a product title that it goes to the page of that product? EX: Every card should go to the exact card page, and when someone clicks on “SOVEREIGN CARD” it goes to the sovereign mirrored card page?

2. Can every time you click the card and the card title it should redirect to the individual card page

**Comment by erikrakuscek** [comment]
completed in commit https://github.com/luxfi/web/commit/1039a107792c4977343ecb310aeb48bcbff1b8b0

**Comment by erikrakuscek** [comment]
TODO: make card clickthrough on browse cards carousel too
