### ISSUE TITLE
issue#235 change "+ add " to "add +", complete mobile menu

### ISSUE THREAD

**Issue by zoosos** [luxfi/web#247]
![image](https://github.com/luxfi/web/assets/92065535/16a1ae91-b670-4347-89dc-9a984ac0c8c4)
change "+"'s position to right of "add".
![image](https://github.com/luxfi/web/assets/92065535/ee81b2f5-8b32-4f04-9a47-0cc5d310b965)
complete make mobile menu

**Comment by wBeanPro** [comment]
https://ui.shadcn.com/docs/components/navigation-menu#link-component for top dev
using above component for

**Comment by wBeanPro** [comment]
![image](https://github.com/luxfi/web/assets/92065535/46b8ee4f-7e17-4900-84ca-782d6947aa2f)
![image](https://github.com/luxfi/web/assets/92065535/d9edef1f-d6e9-4d3e-8710-a4902a0681ab)
![image](https://github.com/luxfi/web/assets/92065535/9f18a004-e93f-4f08-be7d-f2b8cc6113d3)
![image](https://github.com/luxfi/web/assets/92065535/c2796e9c-9802-46f7-ab99-f8c20270773e)

Please check images and let me know what would be better to be changed

**Comment by wBeanPro** [comment]
![image](https://github.com/luxfi/web/assets/92065535/30d6bf95-6d8f-483b-a3a2-2098aec08101)
changed "+" position to right.

**Comment by wBeanPro** [comment]
![image](https://github.com/luxfi/web/assets/92065535/2a49f310-39b7-4882-a262-827ee9735c0f)
footer on the mobile

**Comment by wBeanPro** [comment]
![image](https://github.com/luxfi/web/assets/92065535/43b27b5e-afe3-4e29-b34c-a78cb0f403eb)
changed footer's style
![image](https://github.com/luxfi/web/assets/92065535/f3d67ef0-0a99-406e-89a0-d9da47eadb15)
