### ISSUE TITLE
Drawer on lux.market not responsive

### ISSUE THREAD

**Issue by zeekay** [luxfi/web#249]
![Screenshot 2024-06-04 at 11 41 24 PM](https://github.com/luxfi/web/assets/285707/dac2e237-7eb8-4874-80f5-b15a253f2592)

**Comment by artemis-prime** [comment]
Is this the same issue as the layout having too much neg space?

**Comment by artemis-prime** [comment]
I realize I can make it do more than percent or fixed pixels.  It complicates the task, but it might be worth it.  

I'm assuming you mean the space.  Rt now buttons are glued to bottom, rest to top. And desktop is 75% of height.  

I'll play w it

**Comment by artemis-prime** [comment]
PR 251 turned out to be unrelated
