### ISSUE TITLE
404 menu

### ISSUE THREAD

**Issue by zooqueen** [luxfi/web#271]
Use this as the 404 menu instead, just add component to project 

npx v0 add HugN0K8ixFp 

<img width="363" alt="Untitled 11" src="https://github.com/luxfi/web/assets/98129351/51fb3e7e-ae65-49a8-a8e7-1fd24d28142e">
<img width="1000" alt="Untitled 10" src="https://github.com/luxfi/web/assets/98129351/6dc333db-b268-4eff-97f7-f51b90e164d2">

**Comment by zeekay** [comment]
Content on this page should be:

You are logged in as <z@zeekay.io>. Or if not logged in "This page does not exist". Add "Sign in to your account" white button and then some links at bottom:

[Docs](https://vercel.com/docs)

[Guides](https://vercel.com/guides)

[Blog](https://vercel.com/blog)

**Comment by musordmt** [comment]
Please give me sample content layout of this page.

**Comment by zeekay** [comment]
![Screenshot 2024-07-05 at 5 49 30 PM](https://github.com/luxfi/web/assets/285707/077b841c-2e9f-4bd8-9044-043c81ce7fa7)

**Comment by musordmt** [comment]
Okay, I will make update soon.
