### ISSUE TITLE
feature/make sure the menu same with hanzoai's desktop menu.

### ISSUE THREAD

**Issue by zoosos** [luxfi/web#276]
![image](https://github.com/luxfi/web/assets/92065535/9c3fb0d8-a949-4e12-89ae-1903f70a39ab)
1. Menu should be same as on Hanzo, on the slide up micro drawer, make it same bg as header with the slight 0.9% opacity showing the blur under neath on scroll.
2. hide the handle so it's smooth.

**Comment by zoosos** [comment]
The menus should be slightly translucent and make sure that the two pan colors extend completely on left/right.
fix the typography so body text is slightly darker.

**Comment by zoosos** [comment]
also make sure the responsive for Navigationmenucontents.
![image](https://github.com/luxfi/web/assets/92065535/476c0eca-7e00-432e-b8ec-9f47dc369461)

**Comment by haoliu716** [comment]
[PR/278](https://github.com/luxfi/web/pull/278) opened
