### ISSUE TITLE
checkout: cart should be visible and checkout possible from all sites

### ISSUE THREAD

**Issue by zeekay** [luxfi/web#79]
Right now the cart is not tracking across sites, it should show cart for all sites in a unified way and checkout should be possible after visiting lux.chat, then going to lux.network to read about network, then adding cards on lux.credit etc.

**Comment by artemis-prime** [comment]
Do we still want this if we're migrating to the lux.shop concept ? @zeekay

**Comment by artemis-prime** [comment]
Depends on #82
