### ISSUE TITLE
checkout: enable promo / discount codes / gift cards

### ISSUE THREAD

**Issue by zeekay** [luxfi/web#81]
We need to be able to track when someone visits by a special link (say lux.link/nasser) and then apply a 20% discount (or whatever code). we need both one-time and many use coupons. Here is UI missing from checkout:

![Screenshot 2024-03-18 at 3 47 31 PM](https://github.com/luxdefi/sites/assets/285707/6f967367-34c8-4939-95bb-cce8d9d94d86)

**Comment by aljosaRakita** [comment]
Mock logic on next api, host a json with coupon codes and check if the input code is on the list. If it is on the list apply discount, otherwise say invalid code. Also input code automatically from url query if present.
