### ISSUE TITLE
link: Migrate from linktre.ee to custom site

### ISSUE THREAD

**Issue by zeekay** [luxfi/web#96]
We should port all site content from https://lux.link (which currently uses linktr.ee to our own site which can have our AI and checkout embedded and be more easily customized as well as track conversions and have nicer social sharing pages, etc.

**Comment by artemis-prime** [comment]
Is this more like an Epic?  How many sites are left? Can you clarify this pelase?

**Comment by zeekay** [comment]
https://linktr.ee/luxdefi <- this has all content its just a bunch of buttons on one page.

**Comment by artemis-prime** [comment]
Are you just asking to re-create a version of that, but just built on our platform? @zeekay

**Comment by zeekay** [comment]
Yes.

**Comment by zeekay** [comment]
This is now done.
